apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  labels:
    app: sso
spec:
  instances: 1
  externalAccess:
    enabled: False
  podDisruptionBudget:
    enabled: True
  # User needs to provision the external database
  externalDatabase:
    enabled: False
