apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
spec:
  rules:
  - host: keycloak-test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-discovery
            port:
              number: 8080
